### ISSUE TITLE
Space Ace II: Borf's Revenge (2022)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoAppleIIGS#15]
Genre: Arcade
Year: 2022 
Publisher: Brutal Deluxe Software
Developers: Antoine Vignau & Olivier Zardini
System Requirements: | Apple IIgs ROM 01/3 with 1 MB RAM, one 3.5" disk drive, System 5.0.4
Recommended: | Apple IIgs ROM 01/3 with 4 MB RAM, accelerator card, hard drive, System 6.0.1
Control: numeric keypad on the keyboard/the arrow keys. The directions you will need are UP (8), DOWN (5), LEFT (4) and RIGHT (6). To use Ace's laster gun or staff you may press the '0' on the keypad or press ENTER or SPACE keys.
Language: english
Format: PO Hard Drive image (6 MB) & PO Floppy Disks (8 x 800 KB)
more info here: https://www.brutaldeluxe.fr/products/apple2gs/spaceace2/index.html

Added to the github eXoAppleIIGS "Game Submisson" folder

**Comment by Python-Exoproject** [comment]
Now in WIP version of eXoAppleIIGS
