### ISSUE TITLE
Bigjims other games to consider

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoAppleIIGS#17]
From Bigjim:

Here is a list of demos or games found on the web. Unfortunatly I can't run many of these games

Educational:
~~Cartooners~~ In WIP of eXoAppleIIGS
~~Formulate~~ In WIP of eXoAppleIIGS
~~Inner Body Works~~ See #21 
~~Music shapes (full game and demo )~~ In WIP of eXoAppleIIGS
~~National Geographic Kids Network~~ See #53 (This is a communication program requiring modems)
~~SmoothTalker~~ In WIP of eXoAppleIIGS
~~Super Award Maker~~ See #52 
~~Jam Session (1989)~~ In WIP of eXoAppleIIGS
~~Newspaper Maker~~ See #54 

-Games:
~~Space Ace II : Borf's Revenge (2022)~~ In WIP of eXoAppleIIGS
~~Silent Service (1987)~~ See #23 
~~Star Trek Classic~~ See #30 
~~Canal Meurtre (multilingual)~~ In WIP of eXoAppleIIGS
~~Passengers on the Wind II (2022)~~ In WIP of eXoAppleIIGS
~~L'Égérie (multilingual)(2022)~~ In WIP of eXoAppleIIGS
~~Night Driver (2021)~~ In WIP of eXoAppleIIGS
~~The Dungeons of Fangborne Keep~~ See #51 

~~-DeluxeWare CD:
the first French cd-rom dedicated to the Apple IIgs.  It contains 650 MB of public domain software:
Apple programs, Documentations, Creative visual, Hypermedia, Games, Music, System, Utilities~~ Didnt see any games that are not already included

-Game Demos or unfinished games
~~Last Rites~~ In WIP of eXoAppleIIGS
~~Base Ten Blocks~~ In WIP of eXoAppleIIGS
~~Space Harrier~~ In WIP of eXoAppleIIGS
~~Blue Helmet~~ In WIP of eXoAppleIIGS
~~Oil Landers~~ In WIP of eXoAppleIIGS
~~Pangea 24 Hour Games~~ Pack of 3 games. Included in eXoAppleIIGS individually
~~Time lord~~ In WIP of eXoAppleIIGS
~~Opale~~ In WIP of eXoAppleIIGS
~~1942~~ In WIP of eXoAppleIIGS
~~Bugs Bannis~~ Doesnt seem to be more than a bunch of level files on the disk
~~Le Manoir de Mortevielle~~ In WIP of eXoAppleIIGS

**Comment by bigjim161** [comment]
I added these games to the github folder 'dropbox\SynologyDrive\GitHub\EXOAPPLEIIGS\Game Submission'
