### ISSUE TITLE
Sensei (1991)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoAppleIIGS#39]
Game needs joystick mapped to keyboard\mouse as its a joystick game. Only GSPort and MAME do so properly. While MAME is the preferred option due to limitations in GSPort, this game is currently using GSPort as MAME is not a viable option. Additionally, in GSport the mapped keyboard controls are very unresponsive. The problem in MAME is that it doesnt boot the game, instead it gives an error

**Comment by Torquemurder** [comment]
This game works just fine in MAME 0.250 (and older, presumably); it just needs to booted from slot 5 with -flop3, rather than -hard1, due to its custom trackloader.

**Comment by Python-Exoproject** [comment]
Fixed
