### ISSUE TITLE
Xenocide (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoAppleIIGS#42]
Game needs joystick mapped to keyboard\mouse as its a joystick game. Only GSPort and MAME do so properly. While MAME is the preferred option due to limitations in GSPort, this game is currently using GSPort as MAME is not a viable option. In this case MAME works with the game but the joystick works differently as the control becomes on\off to max signal, compared to GSport where its gradual and sets back to zero. If MAME could use mouse to emulate joystick MAME would be best (see #19).

**Comment by Torquemurder** [comment]
It works fine in MAME, although you have to adjust the sensitivity of the joystick.  Like all MAME titles the X & Y Joystick Sensitivity needs to be set to 1.  It's SUPER sensitive, though and playing with a proper analog joystick like a flight stick is recommended.

**Comment by Python-Exoproject** [comment]
Fixed for mouse emulating joystick when user not using a joystick style controller
