### ISSUE TITLE
War In Middle Earth (1989)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoAppleIIGS#49]
Using GSPlus, however there is a cursor issue which results in trouble selecting most screen items making the game difficult if not impossible to play. 

I would prefer to use MAME but in this game it has numerous issues including graphical glitches on the map, crashing while on the map, and one time while walking along the first few screens I was shown the end game scene and told I had won.

**Comment by Torquemurder** [comment]
You're right about the mouse. GSPlus seems to not have the ability to lock the mouse to window.  I tried this in MAME and it seemed to work fine in ROM 01 mode and 2.8ghz.  I play at 8Ghz for a bit and it seems okay as well.

**Comment by Python-Exoproject** [comment]
Fixed
