### ISSUE TITLE
Apple II games that are incompatible with IIGS?

### ISSUE THREAD

**Issue by Torinde** [exoscoriae/eXoAppleIIGS#63]
Apple claimed that the IIGS was 95% compatible with contemporary Apple II software. (per [Wikipedia](https://en.wikipedia.org/wiki/Apple_IIGS#8-bit_Apple_II_compatibility))
- are there any games in those ~5%? can they be added as eXoAppleII?

**Comment by Python-Exoproject** [comment]
Im not sure I follow. This is a 2GS pack which only has 2GS games so any Apple II software is irrelevant to this pack, and as for the Apple II pack it will include everything we can find for the Apple II

**Comment by Torinde** [comment]
OK. I thought that both types were included, because "IIGS is compatible with II software" (or "95%" of it)

**Comment by gitscosh** [comment]
I think you have that backwards. 95% of IIe software is compatible with the IIGS.
