### ISSUE TITLE
Pirates! (1988)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoAppleIIGS#64]
Game cant save.

We are currently using MAME for this game. For the games internal save feature it requires a floppy to be in the second floppy drive. I can create the floppy image and mount it using the -flop4 command line argument but the game cant write to it as MAME seems to mount floppies in read only by default and I have not discovered a way to mount as write enabled from the command line. 

You can mount write enabled from inside the MAME UI and the game then reads the floppy and works, but obviously we need the command line option to work.

A temporary work around is using MAME save states with shift+f7 and f7 once the MAME UI is enabled with scroll lock

**Comment by Torquemurder** [comment]
This can be fixed by mounting the game using -flop3 instead of -hard1

**Comment by Python-Exoproject** [comment]
Thanks @Torquemurder, that fixed it
